CREATE TABLE stocks(
	id INT(12) PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
	stock_code VARCHAR(8) NOT NULL COMMENT '股票代码',
	stock_name VARCHAR(12) NOT NULL COMMENT '股票名字',
	OPEN DECIMAL(8, 3) COMMENT '今日开盘价',
	last_day_close DECIMAL(8, 3) COMMENT '昨日收盘价',
	current DECIMAL(8, 3) COMMENT '当前价格',
	high DECIMAL(8, 3) COMMENT '今日最高价',
	low DECIMAL(8, 3) COMMENT '今日最低价',
	bidding_price DECIMAL(8, 3) COMMENT '竞买价，即“买一”报价',
	auction_price DECIMAL(8, 3) COMMENT '竞卖价，即“卖一”报价',
	count_of_trade INT(8) COMMENT '成交的股票数', -- 由于股票交易以一百股为基本单位，所以在使用时，通常把该值除以一百
	amount_of_trade DECIMAL(18, 4) COMMENT '成交金额(单位:元)', -- 为了一目了然，通常以“万元”为成交金额的单位，所以通常把该值除以一万
	count_of_buy1 INT(8) COMMENT '“买一”申请量',
	amount_of_buy1 DECIMAL(8, 3) COMMENT '“买一”报价',
	count_of_buy2 INT(8) COMMENT '“买二”申请量',
	amount_of_buy2 DECIMAL(8, 3) COMMENT '“买二”报价',
	count_of_buy3 INT(8) COMMENT '“买三”申请量',
	amount_of_buy3 DECIMAL(8, 3) COMMENT '“买三”报价',
	count_of_buy4 INT(8) COMMENT '“买四”申请量',
	amount_of_buy4 DECIMAL(8, 3) COMMENT '“买四”报价',
	count_of_buy5 INT(8) COMMENT '“买五”申请量',
	amount_of_buy5 DECIMAL(8, 3) COMMENT '“买五”报价',
	count_of_sale1 INT(8) COMMENT '“卖一”申请量',
	amount_of_sale1 DECIMAL(8, 3) COMMENT '“卖一”报价',
	count_of_sale2 INT(8) COMMENT '“卖二”申请量',
	amount_of_sale2 DECIMAL(8, 3) COMMENT '“卖二”报价',
	count_of_sale3 INT(8) COMMENT '“卖三”申请量',
	amount_of_sale3 DECIMAL(8, 3) COMMENT '“卖三”报价',
	count_of_sale4 INT(8) COMMENT '“卖四”申请量',
	amount_of_sale4 DECIMAL(8, 3) COMMENT '“卖四”报价',
	count_of_sale5 INT(8) COMMENT '“卖五”申请量',
	amount_of_sale5 DECIMAL(8, 3) COMMENT '“卖五”报价',
	trade_date VARCHAR(32) COMMENT '最新交易日期',
	trade_time VARCHAR(32) COMMENT '最新交易时间',
	query_time VARCHAR(32) COMMENT '查询时间');